### ISSUE TITLE
no recent release PRs found

### ISSUE THREAD

**Issue by iceicys** [ridedott/release-me-action#473]
I'm trying out the action for the first time and I'm seeing the following. What haven't I specified?
![image](https://user-images.githubusercontent.com/73564034/104380684-5f749d80-54f9-11eb-8a7d-203e5ab97ba7.png)

` on:
   push:
     branches:
       - main
 name: release-please
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v1.3.0
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: release-please-action`

**Comment by acazacu** [comment]
@iceicys, it looks like you are using a different action: https://github.com/googleapis/release-please.
